<a href="https://colab.research.google.com/github/mnzsdebora/Projeto-Vendas/blob/main/projeto_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Imports

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

#Análise Exploratória e Tratamento dos Dados

In [2]:
df = pd.read_csv('/content/breast-cancer-wisconsin-data_data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [5]:
dicionario = {
    'id': 'id',
    'diagnosis': 'diagnostico',
    'radius_mean': 'raio_medio',
    'texture_mean': 'textura_media',
    'perimeter_mean': 'perimetro_medio',
    'area_mean': 'area_media',
    'smoothness_mean': 'suavidade_media',
    'compactness_mean': 'compacidade_media',
    'concavity_mean': 'concavidade_media',
    'concave points_mean': 'pontos_concavos_media',
    'symmetry_mean': 'simetria_media',
    'fractal_dimension_mean': 'dimensao_fractal_media',

    'radius_se': 'raio_erro_padrao',
    'texture_se': 'textura_erro_padrao',
    'perimeter_se': 'perimetro_erro_padrao',
    'area_se': 'area_erro_padrao',
    'smoothness_se': 'suavidade_erro_padrao',
    'compactness_se': 'compacidade_erro_padrao',
    'concavity_se': 'concavidade_erro_padrao',
    'concave points_se': 'pontos_concavos_erro_padrao',
    'symmetry_se': 'simetria_erro_padrao',
    'fractal_dimension_se': 'dimensao_fractal_erro_padrao',

    'radius_worst': 'raio_pior',
    'texture_worst': 'textura_pior',
    'perimeter_worst': 'perimetro_pior',
    'area_worst': 'area_pior',
    'smoothness_worst': 'suavidade_pior',
    'compactness_worst': 'compacidade_pior',
    'concavity_worst': 'concavidade_pior',
    'concave points_worst': 'pontos_concavos_pior',
    'symmetry_worst': 'simetria_pior',
    'fractal_dimension_worst': 'dimensao_fractal_pior',

    'Unnamed: 32': 'coluna_vazia'
}

df = df.rename(columns=dicionario)
df.head()

,id,diagnostico,raio_medio,textura_media,perimetro_medio,area_media,suavidade_media,compacidade_media,concavidade_media,pontos_concavos_media,...,textura_pior,perimetro_pior,area_pior,suavidade_pior,compacidade_pior,concavidade_pior,pontos_concavos_pior,simetria_pior,dimensao_fractal_pior,coluna_vazia
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [6]:
#Verificando a existência de dados duplicados
df.duplicated().sum()

np.int64(0)

In [7]:
df['diagnostico'].unique()

array(['M', 'B'], dtype=object)

In [8]:
#Transformando a variável 'Diagnóstico' em binário
df['diagnostico_binario'] = df['diagnostico'].map({'M': 0, 'B': 1})
df

,id,diagnostico,raio_medio,textura_media,perimetro_medio,area_media,suavidade_media,compacidade_media,concavidade_media,pontos_concavos_media,...,perimetro_pior,area_pior,suavidade_pior,compacidade_pior,concavidade_pior,pontos_concavos_pior,simetria_pior,dimensao_fractal_pior,coluna_vazia,diagnostico_binario
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN,0
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN,0
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN,0
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN,0
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN,0
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN,0
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN,0
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN,0
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN,1

In [9]:
df = df.drop(columns=['coluna_vazia'])
df.head()

,id,diagnostico,raio_medio,textura_media,perimetro_medio,area_media,suavidade_media,compacidade_media,concavidade_media,pontos_concavos_media,...,textura_pior,perimetro_pior,area_pior,suavidade_pior,compacidade_pior,concavidade_pior,pontos_concavos_pior,simetria_pior,dimensao_fractal_pior,diagnostico_binario
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [10]:
#Verificando a existência de dados nulos
df.isnull().sum()

id                              0
diagnostico                     0
raio_medio                      0
textura_media                   0
perimetro_medio                 0
area_media                      0
suavidade_media                 0
compacidade_media               0
concavidade_media               0
pontos_concavos_media           0
simetria_media                  0
dimensao_fractal_media          0
raio_erro_padrao                0
textura_erro_padrao             0
perimetro_erro_padrao           0
area_erro_padrao                0
suavidade_erro_padrao           0
compacidade_erro_padrao         0
concavidade_erro_padrao         0
pontos_concavos_erro_padrao     0
simetria_erro_padrao            0
dimensao_fractal_erro_padrao    0
raio_pior                       0
textura_pior                    0
perimetro_pior                  0
area_pior                       0
suavidade_pior                  0
compacidade_pior                0
concavidade_pior                0
pontos_concavos_pior            0
simetria_pior                   0
dimensao_fractal_pior           0
diagnostico_binario             0
dtype: int64

In [11]:
#Removendo a variavel 'diagnostico' para utilizar somente a sua forma binária
df = df.drop(['diagnostico'], axis=1)
df.head()

,id,raio_medio,textura_media,perimetro_medio,area_media,suavidade_media,compacidade_media,concavidade_media,pontos_concavos_media,simetria_media,...,textura_pior,perimetro_pior,area_pior,suavidade_pior,compacidade_pior,concavidade_pior,pontos_concavos_pior,simetria_pior,dimensao_fractal_pior,diagnostico_binario
0,842302,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [12]:
df.columns

Index(['id', 'raio_medio', 'textura_media', 'perimetro_medio', 'area_media',
       'suavidade_media', 'compacidade_media', 'concavidade_media',
       'pontos_concavos_media', 'simetria_media', 'dimensao_fractal_media',
       'raio_erro_padrao', 'textura_erro_padrao', 'perimetro_erro_padrao',
       'area_erro_padrao', 'suavidade_erro_padrao', 'compacidade_erro_padrao',
       'concavidade_erro_padrao', 'pontos_concavos_erro_padrao',
       'simetria_erro_padrao', 'dimensao_fractal_erro_padrao', 'raio_pior',
       'textura_pior', 'perimetro_pior', 'area_pior', 'suavidade_pior',
       'compacidade_pior', 'concavidade_pior', 'pontos_concavos_pior',
       'simetria_pior', 'dimensao_fractal_pior', 'diagnostico_binario'],
      dtype='object')

#Treinamento de Modelos de Machine Learning

In [13]:
#Divisão entre treino e teste
x = df.drop('diagnostico_binario', axis = 1)
y = df['diagnostico_binario']

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, stratify = y, random_state = 5, test_size = 0.25)

#Utilizando o DummyClassifier como modelo de Based Line
dummy = DummyClassifier()
dummy.fit(x_treino, y_treino)

#Árvore de Decisão
arvore = DecisionTreeClassifier(max_depth = 3, random_state = 5)
arvore.fit(x_treino, y_treino)

#KNN
normalizacao = MinMaxScaler() #normalizando os dados para utilizar o modelo
x_treino_normalizado = normalizacao.fit_transform(x_treino)
knn = KNeighborsClassifier()
knn.fit(x_treino_normalizado, y_treino)
x_teste_normalizado = normalizacao.transform(x_teste)

#SVC
SEED = 5
np.random.seed(SEED)
raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25,
                                                         stratify = y)
#Ajustando a escala para o SVC
scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

modelo = SVC(gamma='auto')
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia_svc = accuracy_score(teste_y, previsoes)

#Acurácia dos modelos treinados
print(f'Acurácia Dummy: {dummy.score(x_teste, y_teste)}')
print(f'Acurácia Árvore: {arvore.score(x_teste, y_teste)}')
print(f'Acurácia KNN: {knn.score(x_teste_normalizado, y_teste)}')
print(f'Acurácia SVC: {acuracia_svc}')

Acurácia Dummy: 0.6293706293706294
Acurácia Árvore: 0.9440559440559441
Acurácia KNN: 0.972027972027972
Acurácia SVC: 0.9790209790209791

#Conclusão

Dentre os modelos treinados, o SVC foi o que obteve uma melhor resposta utilizando a acurácia como métrica de avaliação do modelo, chegando em um valor de 97,9% de acurácia, podendo auxiliar médicos em tomadas de decisões clínicas.